### PR TITLE
Role label rework

### LINKED ISSUE #433: Mafia teammate getting converted rolelabel
If your teammate is converted to another role, their role label should vanish. If they leave your team you wont see it anymore, if they are still on your team you will see the new role.

Fix idea

Rolelabel should be a Boolean
If you can see someone's role label, it is always accurate.
When you are converted your label goes away.

If you don't want this to happen, don't give them a label because it's confusing to have a wrong label

### LINKED ISSUE #511: Someone joined the cult message
When someone is converted to a cult member a message should be sent in chat saying they are now a cultist

INSTEAD when you gain someone's role label you should see a message saying "you can now see that Sammy is a zealot"

### PR DESCRIPTION
**Pull request by ItsSammyM**
closes #433
closes #511

### CODE REVIEW

File: client/src/menu/game/gameScreenContent/PlayerListMenu.tsx [hunk 1]
```diff
@@ -89,19 +111,27 @@ export default class PlayerListMenu extends React.Component<PlayerListMenuProps,
                 case "yourPlayerTags":
                 case "yourRoleLabels":
                 case "playerVotes":
-                    this.setState({ players: GAME_MANAGER.state.players })
+                    this.setState({ players: GAME_MANAGER.state.players });
+                    this.setState({ graveRoles: getRolesFromGraves(GAME_MANAGER.state.graves, GAME_MANAGER.state.players.length) });
```
Comment (Jack-Papel) [inline client/src/menu/game/gameScreenContent/PlayerListMenu.tsx:115]: This only needs to be invoked on the role labels packet, not all three

Comment (Jack-Papel) [reply client/src/menu/game/gameScreenContent/PlayerListMenu.tsx:115]: Actually I don't think it needs to be invoked by any of these

File: client/src/resources/lang/en_us.json [hunk 2]
```diff
@@ -667,7 +669,7 @@
...
+    "wiki.article.standard.roleLabel.text": "- Role labels appear next to player names, it shows what role that player is\n- Role labels are not always public, for example, you can see your own role label at all times, but other players can not\n- A mafia member can see the other mafia members role labels\n- When you gain a role label on another player, you get a chat message saying that players role was revealed to you\n- When you lose a role label on another player, you get a chat message saying that players role was concealed from you\n- If a player that is revealed to you switches roles or dies, their role label will be concealed\n- Dead players can not have role lables, the role that appears next to their name is just the role on their grave. These can be innacurate for reasons like the janitor or forgers ability",
```
Comment (Jack-Papel) [inline client/src/resources/lang/en_us.json:672]: forger's
lables

Install a spellcheck extension 🤬

**Review by Jack-Papel — APPROVED** [review]
You must install a spellcheck extension before you merge this pull request.
Address comments of course.
I didn't test this
